/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PriceStabilizerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autoStabilizeEnabled"
      | "calculateBuyAmount"
      | "calculateDeviation"
      | "calculateSellAmount"
      | "checkStabilizeNeeded"
      | "emergencyWithdraw"
      | "getCurrentPrice"
      | "getPriceStabilizeStatus"
      | "lastStabilizeTime"
      | "manualBuy"
      | "manualSell"
      | "maxBuyAmount"
      | "maxPrice"
      | "maxSellAmount"
      | "minPrice"
      | "owner"
      | "pancakeSwapPair"
      | "pause"
      | "paused"
      | "priceDeviationThreshold"
      | "renounceOwnership"
      | "rwaToken"
      | "setAutoStabilizeEnabled"
      | "setMaxPrice"
      | "setMinPrice"
      | "setPancakeSwapPair"
      | "setPriceDeviationThreshold"
      | "setSwapContractAddress"
      | "setTargetPrice"
      | "stabilizeCooldown"
      | "stabilizeCount"
      | "stabilizePrice"
      | "swapContractAddress"
      | "targetPrice"
      | "totalBuyAmount"
      | "totalSellAmount"
      | "transferOwnership"
      | "unpause"
      | "usdtToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoStabilizeEnabledUpdated"
      | "BuyExecuted"
      | "MaxPriceUpdated"
      | "MinPriceUpdated"
      | "OwnershipTransferred"
      | "PancakeSwapPairUpdated"
      | "Paused"
      | "PriceDeviationThresholdUpdated"
      | "PriceStabilized"
      | "SellExecuted"
      | "SwapContractAddressUpdated"
      | "TargetPriceUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "autoStabilizeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBuyAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDeviation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSellAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkStabilizeNeeded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceStabilizeStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastStabilizeTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manualBuy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "manualSell",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxBuyAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxSellAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "minPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pancakeSwapPair",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceDeviationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rwaToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAutoStabilizeEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPancakeSwapPair",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceDeviationThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapContractAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stabilizeCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stabilizeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stabilizePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBuyAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSellAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "autoStabilizeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBuyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDeviation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSellAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkStabilizeNeeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceStabilizeStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastStabilizeTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manualBuy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manualSell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxBuyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxSellAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pancakeSwapPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceDeviationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rwaToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAutoStabilizeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPancakeSwapPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceDeviationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stabilizeCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stabilizeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stabilizePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBuyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSellAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
}

export namespace AutoStabilizeEnabledUpdatedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyExecutedEvent {
  export type InputTuple = [
    usdtAmount: BigNumberish,
    rwaAmount: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    usdtAmount: bigint,
    rwaAmount: bigint,
    price: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    usdtAmount: bigint;
    rwaAmount: bigint;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PancakeSwapPairUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceDeviationThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceStabilizedEvent {
  export type InputTuple = [
    currentPrice: BigNumberish,
    targetPrice: BigNumberish,
    deviation: BigNumberish,
    bought: boolean,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    currentPrice: bigint,
    targetPrice: bigint,
    deviation: bigint,
    bought: boolean,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    currentPrice: bigint;
    targetPrice: bigint;
    deviation: bigint;
    bought: boolean;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellExecutedEvent {
  export type InputTuple = [
    rwaAmount: BigNumberish,
    usdtAmount: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    rwaAmount: bigint,
    usdtAmount: bigint,
    price: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    rwaAmount: bigint;
    usdtAmount: bigint;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapContractAddressUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceStabilizer extends BaseContract {
  connect(runner?: ContractRunner | null): PriceStabilizer;
  waitForDeployment(): Promise<this>;

  interface: PriceStabilizerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autoStabilizeEnabled: TypedContractMethod<[], [boolean], "view">;

  calculateBuyAmount: TypedContractMethod<
    [currentPrice: BigNumberish, targetPrice_: BigNumberish],
    [bigint],
    "view"
  >;

  calculateDeviation: TypedContractMethod<
    [currentPrice: BigNumberish, targetPrice_: BigNumberish],
    [bigint],
    "view"
  >;

  calculateSellAmount: TypedContractMethod<
    [currentPrice: BigNumberish, targetPrice_: BigNumberish],
    [bigint],
    "view"
  >;

  checkStabilizeNeeded: TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint, boolean] & {
        needStabilize: boolean;
        currentPrice: bigint;
        deviation: bigint;
        shouldBuy: boolean;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  getPriceStabilizeStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint] & {
        currentPrice: bigint;
        targetPrice_: bigint;
        deviation: bigint;
        needStabilize: boolean;
        stabilizeCount_: bigint;
      }
    ],
    "view"
  >;

  lastStabilizeTime: TypedContractMethod<[], [bigint], "view">;

  manualBuy: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  manualSell: TypedContractMethod<
    [rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  maxBuyAmount: TypedContractMethod<[], [bigint], "view">;

  maxPrice: TypedContractMethod<[], [bigint], "view">;

  maxSellAmount: TypedContractMethod<[], [bigint], "view">;

  minPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pancakeSwapPair: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  priceDeviationThreshold: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rwaToken: TypedContractMethod<[], [string], "view">;

  setAutoStabilizeEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setMaxPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPancakeSwapPair: TypedContractMethod<
    [_pancakeSwapPair: AddressLike],
    [void],
    "nonpayable"
  >;

  setPriceDeviationThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSwapContractAddress: TypedContractMethod<
    [_swapContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setTargetPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  stabilizeCooldown: TypedContractMethod<[], [bigint], "view">;

  stabilizeCount: TypedContractMethod<[], [bigint], "view">;

  stabilizePrice: TypedContractMethod<[], [void], "nonpayable">;

  swapContractAddress: TypedContractMethod<[], [string], "view">;

  targetPrice: TypedContractMethod<[], [bigint], "view">;

  totalBuyAmount: TypedContractMethod<[], [bigint], "view">;

  totalSellAmount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdtToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autoStabilizeEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateBuyAmount"
  ): TypedContractMethod<
    [currentPrice: BigNumberish, targetPrice_: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateDeviation"
  ): TypedContractMethod<
    [currentPrice: BigNumberish, targetPrice_: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateSellAmount"
  ): TypedContractMethod<
    [currentPrice: BigNumberish, targetPrice_: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkStabilizeNeeded"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint, boolean] & {
        needStabilize: boolean;
        currentPrice: bigint;
        deviation: bigint;
        shouldBuy: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPriceStabilizeStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint] & {
        currentPrice: bigint;
        targetPrice_: bigint;
        deviation: bigint;
        needStabilize: boolean;
        stabilizeCount_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastStabilizeTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualBuy"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "manualSell"
  ): TypedContractMethod<[rwaAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "maxBuyAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSellAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pancakeSwapPair"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "priceDeviationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rwaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAutoStabilizeEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPancakeSwapPair"
  ): TypedContractMethod<[_pancakeSwapPair: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceDeviationThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSwapContractAddress"
  ): TypedContractMethod<
    [_swapContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTargetPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stabilizeCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stabilizeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stabilizePrice"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "targetPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBuyAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSellAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AutoStabilizeEnabledUpdated"
  ): TypedContractEvent<
    AutoStabilizeEnabledUpdatedEvent.InputTuple,
    AutoStabilizeEnabledUpdatedEvent.OutputTuple,
    AutoStabilizeEnabledUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BuyExecuted"
  ): TypedContractEvent<
    BuyExecutedEvent.InputTuple,
    BuyExecutedEvent.OutputTuple,
    BuyExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MaxPriceUpdated"
  ): TypedContractEvent<
    MaxPriceUpdatedEvent.InputTuple,
    MaxPriceUpdatedEvent.OutputTuple,
    MaxPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinPriceUpdated"
  ): TypedContractEvent<
    MinPriceUpdatedEvent.InputTuple,
    MinPriceUpdatedEvent.OutputTuple,
    MinPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PancakeSwapPairUpdated"
  ): TypedContractEvent<
    PancakeSwapPairUpdatedEvent.InputTuple,
    PancakeSwapPairUpdatedEvent.OutputTuple,
    PancakeSwapPairUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PriceDeviationThresholdUpdated"
  ): TypedContractEvent<
    PriceDeviationThresholdUpdatedEvent.InputTuple,
    PriceDeviationThresholdUpdatedEvent.OutputTuple,
    PriceDeviationThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceStabilized"
  ): TypedContractEvent<
    PriceStabilizedEvent.InputTuple,
    PriceStabilizedEvent.OutputTuple,
    PriceStabilizedEvent.OutputObject
  >;
  getEvent(
    key: "SellExecuted"
  ): TypedContractEvent<
    SellExecutedEvent.InputTuple,
    SellExecutedEvent.OutputTuple,
    SellExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SwapContractAddressUpdated"
  ): TypedContractEvent<
    SwapContractAddressUpdatedEvent.InputTuple,
    SwapContractAddressUpdatedEvent.OutputTuple,
    SwapContractAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TargetPriceUpdated"
  ): TypedContractEvent<
    TargetPriceUpdatedEvent.InputTuple,
    TargetPriceUpdatedEvent.OutputTuple,
    TargetPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AutoStabilizeEnabledUpdated(bool)": TypedContractEvent<
      AutoStabilizeEnabledUpdatedEvent.InputTuple,
      AutoStabilizeEnabledUpdatedEvent.OutputTuple,
      AutoStabilizeEnabledUpdatedEvent.OutputObject
    >;
    AutoStabilizeEnabledUpdated: TypedContractEvent<
      AutoStabilizeEnabledUpdatedEvent.InputTuple,
      AutoStabilizeEnabledUpdatedEvent.OutputTuple,
      AutoStabilizeEnabledUpdatedEvent.OutputObject
    >;

    "BuyExecuted(uint256,uint256,uint256,uint256)": TypedContractEvent<
      BuyExecutedEvent.InputTuple,
      BuyExecutedEvent.OutputTuple,
      BuyExecutedEvent.OutputObject
    >;
    BuyExecuted: TypedContractEvent<
      BuyExecutedEvent.InputTuple,
      BuyExecutedEvent.OutputTuple,
      BuyExecutedEvent.OutputObject
    >;

    "MaxPriceUpdated(uint256,uint256)": TypedContractEvent<
      MaxPriceUpdatedEvent.InputTuple,
      MaxPriceUpdatedEvent.OutputTuple,
      MaxPriceUpdatedEvent.OutputObject
    >;
    MaxPriceUpdated: TypedContractEvent<
      MaxPriceUpdatedEvent.InputTuple,
      MaxPriceUpdatedEvent.OutputTuple,
      MaxPriceUpdatedEvent.OutputObject
    >;

    "MinPriceUpdated(uint256,uint256)": TypedContractEvent<
      MinPriceUpdatedEvent.InputTuple,
      MinPriceUpdatedEvent.OutputTuple,
      MinPriceUpdatedEvent.OutputObject
    >;
    MinPriceUpdated: TypedContractEvent<
      MinPriceUpdatedEvent.InputTuple,
      MinPriceUpdatedEvent.OutputTuple,
      MinPriceUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PancakeSwapPairUpdated(address,address)": TypedContractEvent<
      PancakeSwapPairUpdatedEvent.InputTuple,
      PancakeSwapPairUpdatedEvent.OutputTuple,
      PancakeSwapPairUpdatedEvent.OutputObject
    >;
    PancakeSwapPairUpdated: TypedContractEvent<
      PancakeSwapPairUpdatedEvent.InputTuple,
      PancakeSwapPairUpdatedEvent.OutputTuple,
      PancakeSwapPairUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PriceDeviationThresholdUpdated(uint256,uint256)": TypedContractEvent<
      PriceDeviationThresholdUpdatedEvent.InputTuple,
      PriceDeviationThresholdUpdatedEvent.OutputTuple,
      PriceDeviationThresholdUpdatedEvent.OutputObject
    >;
    PriceDeviationThresholdUpdated: TypedContractEvent<
      PriceDeviationThresholdUpdatedEvent.InputTuple,
      PriceDeviationThresholdUpdatedEvent.OutputTuple,
      PriceDeviationThresholdUpdatedEvent.OutputObject
    >;

    "PriceStabilized(uint256,uint256,uint256,bool,uint256,uint256)": TypedContractEvent<
      PriceStabilizedEvent.InputTuple,
      PriceStabilizedEvent.OutputTuple,
      PriceStabilizedEvent.OutputObject
    >;
    PriceStabilized: TypedContractEvent<
      PriceStabilizedEvent.InputTuple,
      PriceStabilizedEvent.OutputTuple,
      PriceStabilizedEvent.OutputObject
    >;

    "SellExecuted(uint256,uint256,uint256,uint256)": TypedContractEvent<
      SellExecutedEvent.InputTuple,
      SellExecutedEvent.OutputTuple,
      SellExecutedEvent.OutputObject
    >;
    SellExecuted: TypedContractEvent<
      SellExecutedEvent.InputTuple,
      SellExecutedEvent.OutputTuple,
      SellExecutedEvent.OutputObject
    >;

    "SwapContractAddressUpdated(address,address)": TypedContractEvent<
      SwapContractAddressUpdatedEvent.InputTuple,
      SwapContractAddressUpdatedEvent.OutputTuple,
      SwapContractAddressUpdatedEvent.OutputObject
    >;
    SwapContractAddressUpdated: TypedContractEvent<
      SwapContractAddressUpdatedEvent.InputTuple,
      SwapContractAddressUpdatedEvent.OutputTuple,
      SwapContractAddressUpdatedEvent.OutputObject
    >;

    "TargetPriceUpdated(uint256,uint256)": TypedContractEvent<
      TargetPriceUpdatedEvent.InputTuple,
      TargetPriceUpdatedEvent.OutputTuple,
      TargetPriceUpdatedEvent.OutputObject
    >;
    TargetPriceUpdated: TypedContractEvent<
      TargetPriceUpdatedEvent.InputTuple,
      TargetPriceUpdatedEvent.OutputTuple,
      TargetPriceUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
