/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StakingContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BUYBACK_FEE_RATE"
      | "DAILY_CAP_MULTIPLIER"
      | "MIN_WITHDRAWAL_AMOUNT"
      | "POOL_FEE_RATE"
      | "SINGLE_CAP_MULTIPLIER"
      | "SOFT_LANDING_REDUCTION_RATE"
      | "SOFT_LANDING_THRESHOLD"
      | "ST_RWA_LOCK_DURATION"
      | "TREASURY_FEE_RATE"
      | "WITHDRAWAL_COOLDOWN"
      | "WITHDRAWAL_FEE_RATE"
      | "backendAddress"
      | "buybackAddress"
      | "calculateWeightedAverageHoldingPeriod"
      | "dailyRewards"
      | "emergencyWithdraw"
      | "getEmergencyWithdrawPreview"
      | "getGlobalCapInfo"
      | "getRWALockedPrincipals"
      | "getRWAStakeInfoForTax"
      | "getReferralInfo"
      | "getTotalDynamicRewardsPaid"
      | "getTotalStaked"
      | "getUSDTLockedPrincipals"
      | "getUserDailyReward"
      | "getUserPersonalCapInfo"
      | "getUserRewards"
      | "getUserStakeInfo"
      | "getUserStakeInfoForTax"
      | "getUserTodayReward"
      | "maxRewardPerCall"
      | "owner"
      | "pause"
      | "paused"
      | "processedStakes"
      | "renounceOwnership"
      | "rwaFlexiblePrincipal"
      | "rwaFlexibleTotalStaked"
      | "rwaLockedPrincipals"
      | "rwaStakes"
      | "rwaToken"
      | "setBuybackAddress"
      | "setMaxRewardPerCall"
      | "setStRWAToken"
      | "setWhitelist"
      | "stRwaToken"
      | "stake"
      | "stakeHistory"
      | "stakeLockPeriods"
      | "stakeRWA"
      | "totalDynamicRewardsPaid"
      | "totalStaked"
      | "totalStakedRWA"
      | "transferOwnership"
      | "treasuryAddress"
      | "unpause"
      | "updateNodeLevel"
      | "updateUserRewards"
      | "usdtFlexiblePrincipal"
      | "usdtFlexibleTotalStaked"
      | "usdtLockedPrincipals"
      | "usdtToken"
      | "users"
      | "whitelist"
      | "withdraw(uint256)"
      | "withdraw(uint256,bool)"
      | "withdrawFlexibleRWAPrincipal"
      | "withdrawFlexibleUSDTPrincipal"
      | "withdrawRWALockedPrincipal"
      | "withdrawRWARewards"
      | "withdrawUSDTPrincipal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackendAddressUpdated"
      | "BuybackAddressUpdated"
      | "CapCheckFailed"
      | "EmergencyWithdrawal"
      | "FlexibleRWAPrincipalWithdrawn"
      | "FlexibleUSDTPrincipalWithdrawn"
      | "MaxRewardPerCallUpdated"
      | "NodeLevelUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "RWAPrincipalWithdrawn"
      | "RWARewardWithdrawn"
      | "RWAStakeEvent"
      | "ReferralBound"
      | "RewardsUpdated"
      | "StRWAMinted"
      | "StRWATokenUpdated"
      | "StakeEvent"
      | "TokensBurned"
      | "TreasuryAddressUpdated"
      | "USDTPrincipalWithdrawn"
      | "Unpaused"
      | "WhitelistUpdated"
      | "WithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BUYBACK_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_CAP_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WITHDRAWAL_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SINGLE_CAP_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOFT_LANDING_REDUCTION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOFT_LANDING_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ST_RWA_LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWAL_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWAL_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backendAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buybackAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateWeightedAverageHoldingPeriod",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmergencyWithdrawPreview",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalCapInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRWALockedPrincipals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRWAStakeInfoForTax",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDynamicRewardsPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDTLockedPrincipals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDailyReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPersonalCapInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakeInfoForTax",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTodayReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRewardPerCall",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedStakes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rwaFlexiblePrincipal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rwaFlexibleTotalStaked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rwaLockedPrincipals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rwaStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rwaToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBuybackAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRewardPerCall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStRWAToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stRwaToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeLockPeriods",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRWA",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDynamicRewardsPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakedRWA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateNodeLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUserRewards",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usdtFlexiblePrincipal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usdtFlexibleTotalStaked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usdtLockedPrincipals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(uint256,bool)",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFlexibleRWAPrincipal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFlexibleUSDTPrincipal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRWALockedPrincipal",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRWARewards",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUSDTPrincipal",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BUYBACK_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_CAP_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WITHDRAWAL_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SINGLE_CAP_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOFT_LANDING_REDUCTION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOFT_LANDING_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ST_RWA_LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAWAL_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAWAL_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backendAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buybackAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateWeightedAverageHoldingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmergencyWithdrawPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalCapInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRWALockedPrincipals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRWAStakeInfoForTax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDynamicRewardsPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDTLockedPrincipals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDailyReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPersonalCapInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakeInfoForTax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTodayReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRewardPerCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rwaFlexiblePrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rwaFlexibleTotalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rwaLockedPrincipals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rwaStakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rwaToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBuybackAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRewardPerCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStRWAToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stRwaToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeLockPeriods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeRWA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDynamicRewardsPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakedRWA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateNodeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUserRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usdtFlexiblePrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usdtFlexibleTotalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usdtLockedPrincipals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(uint256,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFlexibleRWAPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFlexibleUSDTPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRWALockedPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRWARewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUSDTPrincipal",
    data: BytesLike
  ): Result;
}

export namespace BackendAddressUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuybackAddressUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapCheckFailedEvent {
  export type InputTuple = [
    user: AddressLike,
    capType: string,
    limit: BigNumberish,
    requested: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    capType: string,
    limit: bigint,
    requested: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    capType: string;
    limit: bigint;
    requested: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [
    user: AddressLike,
    refundAmount: BigNumberish,
    deductedRewards: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    refundAmount: bigint,
    deductedRewards: bigint
  ];
  export interface OutputObject {
    user: string;
    refundAmount: bigint;
    deductedRewards: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlexibleRWAPrincipalWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlexibleUSDTPrincipalWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    grossAmount: BigNumberish,
    netAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    grossAmount: bigint,
    netAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    grossAmount: bigint;
    netAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxRewardPerCallUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeLevelUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    oldLevel: BigNumberish,
    newLevel: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    oldLevel: bigint,
    newLevel: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    oldLevel: bigint;
    newLevel: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RWAPrincipalWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    lockIndex: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    lockIndex: bigint,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    lockIndex: bigint;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RWARewardWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RWAStakeEventEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    referrer: AddressLike,
    stakeId: BigNumberish,
    timestamp: BigNumberish,
    lockPeriod: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    referrer: string,
    stakeId: bigint,
    timestamp: bigint,
    lockPeriod: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    referrer: string;
    stakeId: bigint;
    timestamp: bigint;
    lockPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralBoundEvent {
  export type InputTuple = [
    user: AddressLike,
    referrer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, referrer: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    referrer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    rwAmount: BigNumberish,
    usdtAmount: BigNumberish,
    stakeId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    rwAmount: bigint,
    usdtAmount: bigint,
    stakeId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    rwAmount: bigint;
    usdtAmount: bigint;
    stakeId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StRWAMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StRWATokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeEventEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    referrer: AddressLike,
    stakeId: BigNumberish,
    timestamp: BigNumberish,
    lockPeriod: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    referrer: string,
    stakeId: bigint,
    timestamp: bigint,
    lockPeriod: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    referrer: string;
    stakeId: bigint;
    timestamp: bigint;
    lockPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBurnedEvent {
  export type InputTuple = [amount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [amount: bigint, timestamp: bigint];
  export interface OutputObject {
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryAddressUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace USDTPrincipalWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    lockIndex: BigNumberish,
    grossAmount: BigNumberish,
    netAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    lockIndex: bigint,
    grossAmount: bigint,
    netAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    lockIndex: bigint;
    grossAmount: bigint;
    netAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalRequestedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingContract extends BaseContract {
  connect(runner?: ContractRunner | null): StakingContract;
  waitForDeployment(): Promise<this>;

  interface: StakingContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BUYBACK_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  DAILY_CAP_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  MIN_WITHDRAWAL_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  POOL_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  SINGLE_CAP_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  SOFT_LANDING_REDUCTION_RATE: TypedContractMethod<[], [bigint], "view">;

  SOFT_LANDING_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  ST_RWA_LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  TREASURY_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  WITHDRAWAL_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  WITHDRAWAL_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  backendAddress: TypedContractMethod<[], [string], "view">;

  buybackAddress: TypedContractMethod<[], [string], "view">;

  calculateWeightedAverageHoldingPeriod: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  dailyRewards: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [lockIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEmergencyWithdrawPreview: TypedContractMethod<
    [user: AddressLike, lockIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        grossRefund: bigint;
        netRefund: bigint;
        elapsedDays: bigint;
        totalLockDays: bigint;
        eligible: boolean;
      }
    ],
    "view"
  >;

  getGlobalCapInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalStaked_: bigint;
        totalRewards_: bigint;
        maxRewards_: bigint;
        currentPercentage_: bigint;
        softLandingActive_: boolean;
      }
    ],
    "view"
  >;

  getRWALockedPrincipals: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint[], bigint[], bigint[], bigint[], boolean[], boolean[]] & {
        stakeIds: bigint[];
        amounts: bigint[];
        lockStartTimes: bigint[];
        lockEndTimes: bigint[];
        canWithdraw: boolean[];
        isWithdrawn: boolean[];
      }
    ],
    "view"
  >;

  getRWAStakeInfoForTax: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { totalStaked_: bigint; weightedAverageTime: bigint }],
    "view"
  >;

  getReferralInfo: TypedContractMethod<
    [userAddress: AddressLike],
    [[string, boolean] & { referrer_: string; hasReferrer_: boolean }],
    "view"
  >;

  getTotalDynamicRewardsPaid: TypedContractMethod<[], [bigint], "view">;

  getTotalStaked: TypedContractMethod<[], [bigint], "view">;

  getUSDTLockedPrincipals: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint[], bigint[], bigint[], bigint[], boolean[], boolean[]] & {
        stakeIds: bigint[];
        amounts: bigint[];
        lockStartTimes: bigint[];
        lockEndTimes: bigint[];
        canWithdraw: boolean[];
        isWithdrawn: boolean[];
      }
    ],
    "view"
  >;

  getUserDailyReward: TypedContractMethod<
    [user: AddressLike, day: BigNumberish],
    [bigint],
    "view"
  >;

  getUserPersonalCapInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalStaked_: bigint;
        totalRewards_: bigint;
        maxRewards_: bigint;
        remainingCap_: bigint;
      }
    ],
    "view"
  >;

  getUserRewards: TypedContractMethod<
    [userAddress: AddressLike],
    [[bigint, bigint] & { rwaPending_: bigint; usdtRewards_: bigint }],
    "view"
  >;

  getUserStakeInfo: TypedContractMethod<
    [userAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        totalStaked_: bigint;
        rwaPending_: bigint;
        usdtRewards_: bigint;
        lastWithdrawTime_: bigint;
        referrer_: string;
        nodeLevel_: bigint;
        firstStakeTime_: bigint;
      }
    ],
    "view"
  >;

  getUserStakeInfoForTax: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { totalStaked_: bigint; weightedAverageTime_: bigint }],
    "view"
  >;

  getUserTodayReward: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  maxRewardPerCall: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processedStakes: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rwaFlexiblePrincipal: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  rwaFlexibleTotalStaked: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  rwaLockedPrincipals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stakeId: bigint;
        totalAmount: bigint;
        principalAmount: bigint;
        lockStartTime: bigint;
        lockEndTime: bigint;
        isWithdrawn: boolean;
        lockPeriod: bigint;
      }
    ],
    "view"
  >;

  rwaStakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, string, bigint, bigint, boolean] & {
        totalStakedRWA: bigint;
        rwaPending: bigint;
        lastWithdrawTime: bigint;
        referrer: string;
        firstStakeTime: bigint;
        nodeLevel: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  rwaToken: TypedContractMethod<[], [string], "view">;

  setBuybackAddress: TypedContractMethod<
    [_buybackAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxRewardPerCall: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStRWAToken: TypedContractMethod<
    [_stRwaToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setWhitelist: TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  stRwaToken: TypedContractMethod<[], [string], "view">;

  stake: TypedContractMethod<
    [amount: BigNumberish, referrer: AddressLike, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, bigint] & { amount: bigint; timestamp: bigint }],
    "view"
  >;

  stakeLockPeriods: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  stakeRWA: TypedContractMethod<
    [amount: BigNumberish, referrer: AddressLike, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalDynamicRewardsPaid: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  totalStakedRWA: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateNodeLevel: TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateUserRewards: TypedContractMethod<
    [
      user: AddressLike,
      rwAmount: BigNumberish,
      usdtAmount: BigNumberish,
      stakeId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usdtFlexiblePrincipal: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  usdtFlexibleTotalStaked: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  usdtLockedPrincipals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stakeId: bigint;
        totalAmount: bigint;
        principalAmount: bigint;
        lockStartTime: bigint;
        lockEndTime: bigint;
        isWithdrawn: boolean;
        lockPeriod: bigint;
      }
    ],
    "view"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint, boolean] & {
        totalStaked: bigint;
        rwaPending: bigint;
        usdtRewards: bigint;
        lastWithdrawTime: bigint;
        referrer: string;
        firstStakeTime: bigint;
        nodeLevel: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  "withdraw(uint256)": TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "withdraw(uint256,bool)": TypedContractMethod<
    [amount: BigNumberish, chooseStRWA: boolean],
    [void],
    "nonpayable"
  >;

  withdrawFlexibleRWAPrincipal: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFlexibleUSDTPrincipal: TypedContractMethod<[], [void], "nonpayable">;

  withdrawRWALockedPrincipal: TypedContractMethod<
    [lockIndex: BigNumberish, chooseStRWA: boolean],
    [void],
    "nonpayable"
  >;

  withdrawRWARewards: TypedContractMethod<
    [amount: BigNumberish, chooseStRWA: boolean],
    [void],
    "nonpayable"
  >;

  withdrawUSDTPrincipal: TypedContractMethod<
    [lockIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BUYBACK_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_CAP_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WITHDRAWAL_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SINGLE_CAP_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOFT_LANDING_REDUCTION_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOFT_LANDING_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ST_RWA_LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WITHDRAWAL_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WITHDRAWAL_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "backendAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "buybackAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateWeightedAverageHoldingPeriod"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyRewards"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[lockIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEmergencyWithdrawPreview"
  ): TypedContractMethod<
    [user: AddressLike, lockIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        grossRefund: bigint;
        netRefund: bigint;
        elapsedDays: bigint;
        totalLockDays: bigint;
        eligible: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGlobalCapInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalStaked_: bigint;
        totalRewards_: bigint;
        maxRewards_: bigint;
        currentPercentage_: bigint;
        softLandingActive_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRWALockedPrincipals"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint[], bigint[], bigint[], bigint[], boolean[], boolean[]] & {
        stakeIds: bigint[];
        amounts: bigint[];
        lockStartTimes: bigint[];
        lockEndTimes: bigint[];
        canWithdraw: boolean[];
        isWithdrawn: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRWAStakeInfoForTax"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { totalStaked_: bigint; weightedAverageTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReferralInfo"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [[string, boolean] & { referrer_: string; hasReferrer_: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalDynamicRewardsPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUSDTLockedPrincipals"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint[], bigint[], bigint[], bigint[], boolean[], boolean[]] & {
        stakeIds: bigint[];
        amounts: bigint[];
        lockStartTimes: bigint[];
        lockEndTimes: bigint[];
        canWithdraw: boolean[];
        isWithdrawn: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDailyReward"
  ): TypedContractMethod<
    [user: AddressLike, day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPersonalCapInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalStaked_: bigint;
        totalRewards_: bigint;
        maxRewards_: bigint;
        remainingCap_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRewards"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [[bigint, bigint] & { rwaPending_: bigint; usdtRewards_: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStakeInfo"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        totalStaked_: bigint;
        rwaPending_: bigint;
        usdtRewards_: bigint;
        lastWithdrawTime_: bigint;
        referrer_: string;
        nodeLevel_: bigint;
        firstStakeTime_: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStakeInfoForTax"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { totalStaked_: bigint; weightedAverageTime_: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTodayReward"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxRewardPerCall"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processedStakes"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rwaFlexiblePrincipal"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rwaFlexibleTotalStaked"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rwaLockedPrincipals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stakeId: bigint;
        totalAmount: bigint;
        principalAmount: bigint;
        lockStartTime: bigint;
        lockEndTime: bigint;
        isWithdrawn: boolean;
        lockPeriod: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rwaStakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, string, bigint, bigint, boolean] & {
        totalStakedRWA: bigint;
        rwaPending: bigint;
        lastWithdrawTime: bigint;
        referrer: string;
        firstStakeTime: bigint;
        nodeLevel: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rwaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBuybackAddress"
  ): TypedContractMethod<[_buybackAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxRewardPerCall"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStRWAToken"
  ): TypedContractMethod<[_stRwaToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWhitelist"
  ): TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stRwaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [amount: BigNumberish, referrer: AddressLike, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, bigint] & { amount: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakeLockPeriods"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakeRWA"
  ): TypedContractMethod<
    [amount: BigNumberish, referrer: AddressLike, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalDynamicRewardsPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStakedRWA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateNodeLevel"
  ): TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUserRewards"
  ): TypedContractMethod<
    [
      user: AddressLike,
      rwAmount: BigNumberish,
      usdtAmount: BigNumberish,
      stakeId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdtFlexiblePrincipal"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdtFlexibleTotalStaked"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdtLockedPrincipals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        stakeId: bigint;
        totalAmount: bigint;
        principalAmount: bigint;
        lockStartTime: bigint;
        lockEndTime: bigint;
        isWithdrawn: boolean;
        lockPeriod: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint, boolean] & {
        totalStaked: bigint;
        rwaPending: bigint;
        usdtRewards: bigint;
        lastWithdrawTime: bigint;
        referrer: string;
        firstStakeTime: bigint;
        nodeLevel: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw(uint256)"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw(uint256,bool)"
  ): TypedContractMethod<
    [amount: BigNumberish, chooseStRWA: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFlexibleRWAPrincipal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFlexibleUSDTPrincipal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRWALockedPrincipal"
  ): TypedContractMethod<
    [lockIndex: BigNumberish, chooseStRWA: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawRWARewards"
  ): TypedContractMethod<
    [amount: BigNumberish, chooseStRWA: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawUSDTPrincipal"
  ): TypedContractMethod<[lockIndex: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BackendAddressUpdated"
  ): TypedContractEvent<
    BackendAddressUpdatedEvent.InputTuple,
    BackendAddressUpdatedEvent.OutputTuple,
    BackendAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BuybackAddressUpdated"
  ): TypedContractEvent<
    BuybackAddressUpdatedEvent.InputTuple,
    BuybackAddressUpdatedEvent.OutputTuple,
    BuybackAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CapCheckFailed"
  ): TypedContractEvent<
    CapCheckFailedEvent.InputTuple,
    CapCheckFailedEvent.OutputTuple,
    CapCheckFailedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "FlexibleRWAPrincipalWithdrawn"
  ): TypedContractEvent<
    FlexibleRWAPrincipalWithdrawnEvent.InputTuple,
    FlexibleRWAPrincipalWithdrawnEvent.OutputTuple,
    FlexibleRWAPrincipalWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FlexibleUSDTPrincipalWithdrawn"
  ): TypedContractEvent<
    FlexibleUSDTPrincipalWithdrawnEvent.InputTuple,
    FlexibleUSDTPrincipalWithdrawnEvent.OutputTuple,
    FlexibleUSDTPrincipalWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MaxRewardPerCallUpdated"
  ): TypedContractEvent<
    MaxRewardPerCallUpdatedEvent.InputTuple,
    MaxRewardPerCallUpdatedEvent.OutputTuple,
    MaxRewardPerCallUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NodeLevelUpdated"
  ): TypedContractEvent<
    NodeLevelUpdatedEvent.InputTuple,
    NodeLevelUpdatedEvent.OutputTuple,
    NodeLevelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RWAPrincipalWithdrawn"
  ): TypedContractEvent<
    RWAPrincipalWithdrawnEvent.InputTuple,
    RWAPrincipalWithdrawnEvent.OutputTuple,
    RWAPrincipalWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RWARewardWithdrawn"
  ): TypedContractEvent<
    RWARewardWithdrawnEvent.InputTuple,
    RWARewardWithdrawnEvent.OutputTuple,
    RWARewardWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RWAStakeEvent"
  ): TypedContractEvent<
    RWAStakeEventEvent.InputTuple,
    RWAStakeEventEvent.OutputTuple,
    RWAStakeEventEvent.OutputObject
  >;
  getEvent(
    key: "ReferralBound"
  ): TypedContractEvent<
    ReferralBoundEvent.InputTuple,
    ReferralBoundEvent.OutputTuple,
    ReferralBoundEvent.OutputObject
  >;
  getEvent(
    key: "RewardsUpdated"
  ): TypedContractEvent<
    RewardsUpdatedEvent.InputTuple,
    RewardsUpdatedEvent.OutputTuple,
    RewardsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StRWAMinted"
  ): TypedContractEvent<
    StRWAMintedEvent.InputTuple,
    StRWAMintedEvent.OutputTuple,
    StRWAMintedEvent.OutputObject
  >;
  getEvent(
    key: "StRWATokenUpdated"
  ): TypedContractEvent<
    StRWATokenUpdatedEvent.InputTuple,
    StRWATokenUpdatedEvent.OutputTuple,
    StRWATokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakeEvent"
  ): TypedContractEvent<
    StakeEventEvent.InputTuple,
    StakeEventEvent.OutputTuple,
    StakeEventEvent.OutputObject
  >;
  getEvent(
    key: "TokensBurned"
  ): TypedContractEvent<
    TokensBurnedEvent.InputTuple,
    TokensBurnedEvent.OutputTuple,
    TokensBurnedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryAddressUpdated"
  ): TypedContractEvent<
    TreasuryAddressUpdatedEvent.InputTuple,
    TreasuryAddressUpdatedEvent.OutputTuple,
    TreasuryAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "USDTPrincipalWithdrawn"
  ): TypedContractEvent<
    USDTPrincipalWithdrawnEvent.InputTuple,
    USDTPrincipalWithdrawnEvent.OutputTuple,
    USDTPrincipalWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalRequested"
  ): TypedContractEvent<
    WithdrawalRequestedEvent.InputTuple,
    WithdrawalRequestedEvent.OutputTuple,
    WithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "BackendAddressUpdated(address,address)": TypedContractEvent<
      BackendAddressUpdatedEvent.InputTuple,
      BackendAddressUpdatedEvent.OutputTuple,
      BackendAddressUpdatedEvent.OutputObject
    >;
    BackendAddressUpdated: TypedContractEvent<
      BackendAddressUpdatedEvent.InputTuple,
      BackendAddressUpdatedEvent.OutputTuple,
      BackendAddressUpdatedEvent.OutputObject
    >;

    "BuybackAddressUpdated(address,address)": TypedContractEvent<
      BuybackAddressUpdatedEvent.InputTuple,
      BuybackAddressUpdatedEvent.OutputTuple,
      BuybackAddressUpdatedEvent.OutputObject
    >;
    BuybackAddressUpdated: TypedContractEvent<
      BuybackAddressUpdatedEvent.InputTuple,
      BuybackAddressUpdatedEvent.OutputTuple,
      BuybackAddressUpdatedEvent.OutputObject
    >;

    "CapCheckFailed(address,string,uint256,uint256,uint256)": TypedContractEvent<
      CapCheckFailedEvent.InputTuple,
      CapCheckFailedEvent.OutputTuple,
      CapCheckFailedEvent.OutputObject
    >;
    CapCheckFailed: TypedContractEvent<
      CapCheckFailedEvent.InputTuple,
      CapCheckFailedEvent.OutputTuple,
      CapCheckFailedEvent.OutputObject
    >;

    "EmergencyWithdrawal(address,uint256,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "FlexibleRWAPrincipalWithdrawn(address,uint256,uint256)": TypedContractEvent<
      FlexibleRWAPrincipalWithdrawnEvent.InputTuple,
      FlexibleRWAPrincipalWithdrawnEvent.OutputTuple,
      FlexibleRWAPrincipalWithdrawnEvent.OutputObject
    >;
    FlexibleRWAPrincipalWithdrawn: TypedContractEvent<
      FlexibleRWAPrincipalWithdrawnEvent.InputTuple,
      FlexibleRWAPrincipalWithdrawnEvent.OutputTuple,
      FlexibleRWAPrincipalWithdrawnEvent.OutputObject
    >;

    "FlexibleUSDTPrincipalWithdrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      FlexibleUSDTPrincipalWithdrawnEvent.InputTuple,
      FlexibleUSDTPrincipalWithdrawnEvent.OutputTuple,
      FlexibleUSDTPrincipalWithdrawnEvent.OutputObject
    >;
    FlexibleUSDTPrincipalWithdrawn: TypedContractEvent<
      FlexibleUSDTPrincipalWithdrawnEvent.InputTuple,
      FlexibleUSDTPrincipalWithdrawnEvent.OutputTuple,
      FlexibleUSDTPrincipalWithdrawnEvent.OutputObject
    >;

    "MaxRewardPerCallUpdated(uint256)": TypedContractEvent<
      MaxRewardPerCallUpdatedEvent.InputTuple,
      MaxRewardPerCallUpdatedEvent.OutputTuple,
      MaxRewardPerCallUpdatedEvent.OutputObject
    >;
    MaxRewardPerCallUpdated: TypedContractEvent<
      MaxRewardPerCallUpdatedEvent.InputTuple,
      MaxRewardPerCallUpdatedEvent.OutputTuple,
      MaxRewardPerCallUpdatedEvent.OutputObject
    >;

    "NodeLevelUpdated(address,uint8,uint8,uint256)": TypedContractEvent<
      NodeLevelUpdatedEvent.InputTuple,
      NodeLevelUpdatedEvent.OutputTuple,
      NodeLevelUpdatedEvent.OutputObject
    >;
    NodeLevelUpdated: TypedContractEvent<
      NodeLevelUpdatedEvent.InputTuple,
      NodeLevelUpdatedEvent.OutputTuple,
      NodeLevelUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RWAPrincipalWithdrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      RWAPrincipalWithdrawnEvent.InputTuple,
      RWAPrincipalWithdrawnEvent.OutputTuple,
      RWAPrincipalWithdrawnEvent.OutputObject
    >;
    RWAPrincipalWithdrawn: TypedContractEvent<
      RWAPrincipalWithdrawnEvent.InputTuple,
      RWAPrincipalWithdrawnEvent.OutputTuple,
      RWAPrincipalWithdrawnEvent.OutputObject
    >;

    "RWARewardWithdrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      RWARewardWithdrawnEvent.InputTuple,
      RWARewardWithdrawnEvent.OutputTuple,
      RWARewardWithdrawnEvent.OutputObject
    >;
    RWARewardWithdrawn: TypedContractEvent<
      RWARewardWithdrawnEvent.InputTuple,
      RWARewardWithdrawnEvent.OutputTuple,
      RWARewardWithdrawnEvent.OutputObject
    >;

    "RWAStakeEvent(address,uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      RWAStakeEventEvent.InputTuple,
      RWAStakeEventEvent.OutputTuple,
      RWAStakeEventEvent.OutputObject
    >;
    RWAStakeEvent: TypedContractEvent<
      RWAStakeEventEvent.InputTuple,
      RWAStakeEventEvent.OutputTuple,
      RWAStakeEventEvent.OutputObject
    >;

    "ReferralBound(address,address,uint256)": TypedContractEvent<
      ReferralBoundEvent.InputTuple,
      ReferralBoundEvent.OutputTuple,
      ReferralBoundEvent.OutputObject
    >;
    ReferralBound: TypedContractEvent<
      ReferralBoundEvent.InputTuple,
      ReferralBoundEvent.OutputTuple,
      ReferralBoundEvent.OutputObject
    >;

    "RewardsUpdated(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RewardsUpdatedEvent.InputTuple,
      RewardsUpdatedEvent.OutputTuple,
      RewardsUpdatedEvent.OutputObject
    >;
    RewardsUpdated: TypedContractEvent<
      RewardsUpdatedEvent.InputTuple,
      RewardsUpdatedEvent.OutputTuple,
      RewardsUpdatedEvent.OutputObject
    >;

    "StRWAMinted(address,uint256,uint256)": TypedContractEvent<
      StRWAMintedEvent.InputTuple,
      StRWAMintedEvent.OutputTuple,
      StRWAMintedEvent.OutputObject
    >;
    StRWAMinted: TypedContractEvent<
      StRWAMintedEvent.InputTuple,
      StRWAMintedEvent.OutputTuple,
      StRWAMintedEvent.OutputObject
    >;

    "StRWATokenUpdated(address,address)": TypedContractEvent<
      StRWATokenUpdatedEvent.InputTuple,
      StRWATokenUpdatedEvent.OutputTuple,
      StRWATokenUpdatedEvent.OutputObject
    >;
    StRWATokenUpdated: TypedContractEvent<
      StRWATokenUpdatedEvent.InputTuple,
      StRWATokenUpdatedEvent.OutputTuple,
      StRWATokenUpdatedEvent.OutputObject
    >;

    "StakeEvent(address,uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      StakeEventEvent.InputTuple,
      StakeEventEvent.OutputTuple,
      StakeEventEvent.OutputObject
    >;
    StakeEvent: TypedContractEvent<
      StakeEventEvent.InputTuple,
      StakeEventEvent.OutputTuple,
      StakeEventEvent.OutputObject
    >;

    "TokensBurned(uint256,uint256)": TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
    TokensBurned: TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;

    "TreasuryAddressUpdated(address,address)": TypedContractEvent<
      TreasuryAddressUpdatedEvent.InputTuple,
      TreasuryAddressUpdatedEvent.OutputTuple,
      TreasuryAddressUpdatedEvent.OutputObject
    >;
    TreasuryAddressUpdated: TypedContractEvent<
      TreasuryAddressUpdatedEvent.InputTuple,
      TreasuryAddressUpdatedEvent.OutputTuple,
      TreasuryAddressUpdatedEvent.OutputObject
    >;

    "USDTPrincipalWithdrawn(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      USDTPrincipalWithdrawnEvent.InputTuple,
      USDTPrincipalWithdrawnEvent.OutputTuple,
      USDTPrincipalWithdrawnEvent.OutputObject
    >;
    USDTPrincipalWithdrawn: TypedContractEvent<
      USDTPrincipalWithdrawnEvent.InputTuple,
      USDTPrincipalWithdrawnEvent.OutputTuple,
      USDTPrincipalWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;

    "WithdrawalRequested(address,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
    WithdrawalRequested: TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
  };
}
