/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface USDTRWASwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRECISION_MULTIPLIER"
      | "PRICE_DENOMINATOR"
      | "PRICE_NUMERATOR"
      | "RWA_DECIMALS"
      | "USDT_DECIMALS"
      | "addLiquidity"
      | "getLiquidity"
      | "getQuoteRWAToUSDT"
      | "getQuoteUSDTToRWA"
      | "maxSwapAmount"
      | "minSwapAmount"
      | "owner"
      | "removeLiquidity"
      | "renounceOwnership"
      | "rwaToken"
      | "setSwapEnabled"
      | "setSwapLimits"
      | "swapEnabled"
      | "swapRWAToUSDT"
      | "swapUSDTToRWA"
      | "transferOwnership"
      | "usdtToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
      | "SwapEnabledUpdated"
      | "SwapLimitsUpdated"
      | "SwapRWAToUSDT"
      | "SwapUSDTToRWA"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PRECISION_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_NUMERATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RWA_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteRWAToUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteUSDTToRWA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSwapAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minSwapAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rwaToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setSwapEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRWAToUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapUSDTToRWA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PRECISION_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_NUMERATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RWA_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteRWAToUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteUSDTToRWA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSwapAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minSwapAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rwaToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSwapEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRWAToUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapUSDTToRWA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [usdtAmount: BigNumberish, rwaAmount: BigNumberish];
  export type OutputTuple = [usdtAmount: bigint, rwaAmount: bigint];
  export interface OutputObject {
    usdtAmount: bigint;
    rwaAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [usdtAmount: BigNumberish, rwaAmount: BigNumberish];
  export type OutputTuple = [usdtAmount: bigint, rwaAmount: bigint];
  export interface OutputObject {
    usdtAmount: bigint;
    rwaAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEnabledUpdatedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapLimitsUpdatedEvent {
  export type InputTuple = [minAmount: BigNumberish, maxAmount: BigNumberish];
  export type OutputTuple = [minAmount: bigint, maxAmount: bigint];
  export interface OutputObject {
    minAmount: bigint;
    maxAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapRWAToUSDTEvent {
  export type InputTuple = [
    user: AddressLike,
    rwaAmount: BigNumberish,
    usdtAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    rwaAmount: bigint,
    usdtAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    rwaAmount: bigint;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapUSDTToRWAEvent {
  export type InputTuple = [
    user: AddressLike,
    usdtAmount: BigNumberish,
    rwaAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    usdtAmount: bigint,
    rwaAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    usdtAmount: bigint;
    rwaAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface USDTRWASwap extends BaseContract {
  connect(runner?: ContractRunner | null): USDTRWASwap;
  waitForDeployment(): Promise<this>;

  interface: USDTRWASwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRECISION_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  PRICE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PRICE_NUMERATOR: TypedContractMethod<[], [bigint], "view">;

  RWA_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  USDT_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish, rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getLiquidity: TypedContractMethod<
    [],
    [[bigint, bigint] & { usdtBalance: bigint; rwaBalance: bigint }],
    "view"
  >;

  getQuoteRWAToUSDT: TypedContractMethod<
    [rwaAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getQuoteUSDTToRWA: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [bigint],
    "view"
  >;

  maxSwapAmount: TypedContractMethod<[], [bigint], "view">;

  minSwapAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [usdtAmount: BigNumberish, rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rwaToken: TypedContractMethod<[], [string], "view">;

  setSwapEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setSwapLimits: TypedContractMethod<
    [_minAmount: BigNumberish, _maxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapEnabled: TypedContractMethod<[], [boolean], "view">;

  swapRWAToUSDT: TypedContractMethod<
    [rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapUSDTToRWA: TypedContractMethod<
    [usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRECISION_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_NUMERATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RWA_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLiquidity"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { usdtBalance: bigint; rwaBalance: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuoteRWAToUSDT"
  ): TypedContractMethod<[rwaAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuoteUSDTToRWA"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSwapAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minSwapAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [usdtAmount: BigNumberish, rwaAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rwaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSwapEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSwapLimits"
  ): TypedContractMethod<
    [_minAmount: BigNumberish, _maxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapRWAToUSDT"
  ): TypedContractMethod<[rwaAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapUSDTToRWA"
  ): TypedContractMethod<[usdtAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SwapEnabledUpdated"
  ): TypedContractEvent<
    SwapEnabledUpdatedEvent.InputTuple,
    SwapEnabledUpdatedEvent.OutputTuple,
    SwapEnabledUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapLimitsUpdated"
  ): TypedContractEvent<
    SwapLimitsUpdatedEvent.InputTuple,
    SwapLimitsUpdatedEvent.OutputTuple,
    SwapLimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapRWAToUSDT"
  ): TypedContractEvent<
    SwapRWAToUSDTEvent.InputTuple,
    SwapRWAToUSDTEvent.OutputTuple,
    SwapRWAToUSDTEvent.OutputObject
  >;
  getEvent(
    key: "SwapUSDTToRWA"
  ): TypedContractEvent<
    SwapUSDTToRWAEvent.InputTuple,
    SwapUSDTToRWAEvent.OutputTuple,
    SwapUSDTToRWAEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SwapEnabledUpdated(bool)": TypedContractEvent<
      SwapEnabledUpdatedEvent.InputTuple,
      SwapEnabledUpdatedEvent.OutputTuple,
      SwapEnabledUpdatedEvent.OutputObject
    >;
    SwapEnabledUpdated: TypedContractEvent<
      SwapEnabledUpdatedEvent.InputTuple,
      SwapEnabledUpdatedEvent.OutputTuple,
      SwapEnabledUpdatedEvent.OutputObject
    >;

    "SwapLimitsUpdated(uint256,uint256)": TypedContractEvent<
      SwapLimitsUpdatedEvent.InputTuple,
      SwapLimitsUpdatedEvent.OutputTuple,
      SwapLimitsUpdatedEvent.OutputObject
    >;
    SwapLimitsUpdated: TypedContractEvent<
      SwapLimitsUpdatedEvent.InputTuple,
      SwapLimitsUpdatedEvent.OutputTuple,
      SwapLimitsUpdatedEvent.OutputObject
    >;

    "SwapRWAToUSDT(address,uint256,uint256)": TypedContractEvent<
      SwapRWAToUSDTEvent.InputTuple,
      SwapRWAToUSDTEvent.OutputTuple,
      SwapRWAToUSDTEvent.OutputObject
    >;
    SwapRWAToUSDT: TypedContractEvent<
      SwapRWAToUSDTEvent.InputTuple,
      SwapRWAToUSDTEvent.OutputTuple,
      SwapRWAToUSDTEvent.OutputObject
    >;

    "SwapUSDTToRWA(address,uint256,uint256)": TypedContractEvent<
      SwapUSDTToRWAEvent.InputTuple,
      SwapUSDTToRWAEvent.OutputTuple,
      SwapUSDTToRWAEvent.OutputObject
    >;
    SwapUSDTToRWA: TypedContractEvent<
      SwapUSDTToRWAEvent.InputTuple,
      SwapUSDTToRWAEvent.OutputTuple,
      SwapUSDTToRWAEvent.OutputObject
    >;
  };
}
