/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStRWA,
  IStRWAInterface,
} from "../../../contracts/StakingContract.sol/IStRWA";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStRWA__factory {
  static readonly abi = _abi;
  static createInterface(): IStRWAInterface {
    return new Interface(_abi) as IStRWAInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IStRWA {
    return new Contract(address, _abi, runner) as unknown as IStRWA;
  }
}
