/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from "./MockERC20__factory";
export { MockPausable__factory } from "./MockPausable__factory";
